apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/crynk-452620/crynk-backend:[IMAGE_TAG]
        env:
        - name: DATABASE_URL
          value: 'mysql://crynk:1NeSSie$21987@/crynk?host=/cloudsql/my-project:us-central1:crynk-mysql-db'
        ports:
        - containerPort: 8080
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        args:
        - "--structured-logs"
        - "--port=3306"
        - "crynk-452620:us-central1:crynk-mysql-db"
        securityContext:
          runAsNonRoot: true
