apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/crynk-452620/crynk-backend:[IMAGE_TAG]
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"  # Fixed
          limits:
            memory: "500Mi"
            cpu: "500m"  # Fixed
        # ... rest unchanged
      - name: cloud-sql-proxy
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        # ... rest unchanged
