name: Deploy Backend to EKS

on:
  push:
    branches:
      - main
  paths:
    - 'backend/**'
    - '.github/workflows/backend-ci.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup default stable

      - name: Build Backend
        run: |
          cd backend
          cargo build --release

     - name: Build and Push Docker Image to ECR
        run: |
          cd backend
          ECR_REPOSITORY=677276115846.dkr.ecr.eu-north-1.amazonaws.com/crynk-backend #ECR URI
          IMAGE_TAG=$(git rev-parse --short HEAD)

          # Replace the image tag in the deployment YAML
          sed -i "s|image:.*|image: $ECR_REPOSITORY:$IMAGE_TAG|" k8s/backend-deployment.yaml
          
          # Build the Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          
          # Push the Docker image to ECR
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name crynk-cluster --region eu-north-1
          kubectl apply -f backend/k8s/backend-deployment.yaml
          kubectl apply -f backend/k8s/backend-service.yaml
