name: Deploy Backend to EKS

on:
  push:
    branches:
      - main
  paths:
    - 'backend/**'
    - '.github/workflows/backend-ci.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup default stable

      - name: Build Backend
        run: |
          cd backend
          cargo build --release

      - name: Build and Push Docker Image
        run: |
          cd backend
          docker build -t your-dockerhub-username/backend:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/backend:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name your-cluster-name --region your-region
          kubectl apply -f backend/k8s/deployment.yaml
          kubectl apply -f backend/k8s/service.yaml
