name: Deploy Frontend to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/front-end.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies & Build React
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build and Push Docker Image
        run: |
          cd frontend
          docker build -t your-dockerhub-username/frontend:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/frontend:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name your-cluster-name --region your-region
          kubectl apply -f frontend/k8s/deployment.yaml
          kubectl apply -f frontend/k8s/service.yaml
