name: Deploy Frontend to EKS

on:
  push:
    branches:
      - main  # Runs when pushing to main branch
    paths:
      - 'frontend/**'  # Runs when changes are made in the frontend directory
      - '.github/workflows/deploy-frontend.yml'  # Runs when changes are made in the workflow file

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies & Build React
        run: |
          cd frontend
          npm install
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  #AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image to ECR
        run: |
          cd frontend
          ECR_REPOSITORY=677276115846.dkr.ecr.eu-north-1.amazonaws.com/crynk-frontend #ECR URI
          IMAGE_TAG=$(git rev-parse --short HEAD)

          # Replace the image tag in the deployment YAML
          sed -i "s|image:.*|image: $ECR_REPOSITORY:$IMAGE_TAG|" k8s/frontend-deployment.yaml
          
          # Build the Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          
          # Push the Docker image to ECR
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name crynk-cluster --region eu-north-1
          kubectl apply -f frontend/k8s/frontend-deployment.yaml
          kubectl apply -f frontend/k8s/frontend-service.yaml
