name: Deploy Frontend to GKE

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies & Build React
        run: |
          cd frontend
          npm install
          npm run build

      - name: Activate Account
        run: gcloud config set account github-developer@crynk-452620.iam.gserviceaccount.com

      - name: Check Active Account
        run: gcloud auth list

      - name: Test Access Token
        run: gcloud auth print-access-token

      - name: Auth to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

#      - name: Activate Service Account
#        run: |
#          printf '%s' "${{ secrets.GCP_SA_KEY }}" > /tmp/key.json
#          gcloud auth activate-service-account --key-file=/tmp/key.json
#          rm /tmp/key.json

      - name: Authenticate Docker to GCR
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io

      - name: Build and Push Docker Image to GCR
        run: |
          cd frontend
          GCR_REPOSITORY=gcr.io/${{ secrets.GCP_PROJECT_ID }}/crynk-frontend
          IMAGE_TAG=$(git rev-parse --short HEAD)

          # Replace the image tag in the deployment YAML
          sed -i "s|image:.*|image: $GCR_REPOSITORY:$IMAGE_TAG|" k8s/frontend-deployment.yaml
          
          # Build the Docker image
          docker build -t $GCR_REPOSITORY:$IMAGE_TAG .
          
          # Push the Docker image to GCR
          docker push $GCR_REPOSITORY:$IMAGE_TAG
        
      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials crynk-cluster --zone=us-central1-a
          kubectl apply -f frontend/k8s/frontend-deployment.yaml
          kubectl apply -f frontend/k8s/frontend-service.yaml
